theme = "monokai"

[editor]
mouse = false
true-color = true

[editor.auto-pairs]
'(' = ')'
'[' = ']'
'{' = '}'
'"' = '"'

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[keys.normal.space]
w = { x = "wclose" }

[keys.normal.C-w]
x = "wclose"
