[[language]]
name = "markdown"
language-servers = ["markdown-oxide"]
auto-format = true 

[[language]]
name = "go"
roots = ["go.mod"]
auto-format = true
language-servers = ["gopls"]
formatter = { command = "goimports" }
